/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PairingRouteImport } from './routes/pairing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WinesIndexRouteImport } from './routes/wines/index'
import { Route as WineriesIndexRouteImport } from './routes/wineries/index'
import { Route as CellarsIndexRouteImport } from './routes/cellars/index'
import { Route as WinesAddRouteImport } from './routes/wines/add'
import { Route as WineriesAddRouteImport } from './routes/wineries/add'
import { Route as WinesIdIndexRouteImport } from './routes/wines/$id/index'
import { Route as WineriesIdIndexRouteImport } from './routes/wineries/$id/index'
import { Route as WinesIdEditRouteImport } from './routes/wines/$id/edit'
import { Route as WineriesIdEditRouteImport } from './routes/wineries/$id/edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PairingRoute = PairingRouteImport.update({
  id: '/pairing',
  path: '/pairing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WinesIndexRoute = WinesIndexRouteImport.update({
  id: '/wines/',
  path: '/wines/',
  getParentRoute: () => rootRouteImport,
} as any)
const WineriesIndexRoute = WineriesIndexRouteImport.update({
  id: '/wineries/',
  path: '/wineries/',
  getParentRoute: () => rootRouteImport,
} as any)
const CellarsIndexRoute = CellarsIndexRouteImport.update({
  id: '/cellars/',
  path: '/cellars/',
  getParentRoute: () => rootRouteImport,
} as any)
const WinesAddRoute = WinesAddRouteImport.update({
  id: '/wines/add',
  path: '/wines/add',
  getParentRoute: () => rootRouteImport,
} as any)
const WineriesAddRoute = WineriesAddRouteImport.update({
  id: '/wineries/add',
  path: '/wineries/add',
  getParentRoute: () => rootRouteImport,
} as any)
const WinesIdIndexRoute = WinesIdIndexRouteImport.update({
  id: '/wines/$id/',
  path: '/wines/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const WineriesIdIndexRoute = WineriesIdIndexRouteImport.update({
  id: '/wineries/$id/',
  path: '/wineries/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const WinesIdEditRoute = WinesIdEditRouteImport.update({
  id: '/wines/$id/edit',
  path: '/wines/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const WineriesIdEditRoute = WineriesIdEditRouteImport.update({
  id: '/wineries/$id/edit',
  path: '/wineries/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pairing': typeof PairingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/wineries/add': typeof WineriesAddRoute
  '/wines/add': typeof WinesAddRoute
  '/cellars': typeof CellarsIndexRoute
  '/wineries': typeof WineriesIndexRoute
  '/wines': typeof WinesIndexRoute
  '/wineries/$id/edit': typeof WineriesIdEditRoute
  '/wines/$id/edit': typeof WinesIdEditRoute
  '/wineries/$id': typeof WineriesIdIndexRoute
  '/wines/$id': typeof WinesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pairing': typeof PairingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/wineries/add': typeof WineriesAddRoute
  '/wines/add': typeof WinesAddRoute
  '/cellars': typeof CellarsIndexRoute
  '/wineries': typeof WineriesIndexRoute
  '/wines': typeof WinesIndexRoute
  '/wineries/$id/edit': typeof WineriesIdEditRoute
  '/wines/$id/edit': typeof WinesIdEditRoute
  '/wineries/$id': typeof WineriesIdIndexRoute
  '/wines/$id': typeof WinesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pairing': typeof PairingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/wineries/add': typeof WineriesAddRoute
  '/wines/add': typeof WinesAddRoute
  '/cellars/': typeof CellarsIndexRoute
  '/wineries/': typeof WineriesIndexRoute
  '/wines/': typeof WinesIndexRoute
  '/wineries/$id/edit': typeof WineriesIdEditRoute
  '/wines/$id/edit': typeof WinesIdEditRoute
  '/wineries/$id/': typeof WineriesIdIndexRoute
  '/wines/$id/': typeof WinesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/pairing'
    | '/reset-password'
    | '/settings'
    | '/wineries/add'
    | '/wines/add'
    | '/cellars'
    | '/wineries'
    | '/wines'
    | '/wineries/$id/edit'
    | '/wines/$id/edit'
    | '/wineries/$id'
    | '/wines/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/pairing'
    | '/reset-password'
    | '/settings'
    | '/wineries/add'
    | '/wines/add'
    | '/cellars'
    | '/wineries'
    | '/wines'
    | '/wineries/$id/edit'
    | '/wines/$id/edit'
    | '/wineries/$id'
    | '/wines/$id'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/pairing'
    | '/reset-password'
    | '/settings'
    | '/wineries/add'
    | '/wines/add'
    | '/cellars/'
    | '/wineries/'
    | '/wines/'
    | '/wineries/$id/edit'
    | '/wines/$id/edit'
    | '/wineries/$id/'
    | '/wines/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PairingRoute: typeof PairingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  WineriesAddRoute: typeof WineriesAddRoute
  WinesAddRoute: typeof WinesAddRoute
  CellarsIndexRoute: typeof CellarsIndexRoute
  WineriesIndexRoute: typeof WineriesIndexRoute
  WinesIndexRoute: typeof WinesIndexRoute
  WineriesIdEditRoute: typeof WineriesIdEditRoute
  WinesIdEditRoute: typeof WinesIdEditRoute
  WineriesIdIndexRoute: typeof WineriesIdIndexRoute
  WinesIdIndexRoute: typeof WinesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pairing': {
      id: '/pairing'
      path: '/pairing'
      fullPath: '/pairing'
      preLoaderRoute: typeof PairingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wines/': {
      id: '/wines/'
      path: '/wines'
      fullPath: '/wines'
      preLoaderRoute: typeof WinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wineries/': {
      id: '/wineries/'
      path: '/wineries'
      fullPath: '/wineries'
      preLoaderRoute: typeof WineriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cellars/': {
      id: '/cellars/'
      path: '/cellars'
      fullPath: '/cellars'
      preLoaderRoute: typeof CellarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wines/add': {
      id: '/wines/add'
      path: '/wines/add'
      fullPath: '/wines/add'
      preLoaderRoute: typeof WinesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wineries/add': {
      id: '/wineries/add'
      path: '/wineries/add'
      fullPath: '/wineries/add'
      preLoaderRoute: typeof WineriesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wines/$id/': {
      id: '/wines/$id/'
      path: '/wines/$id'
      fullPath: '/wines/$id'
      preLoaderRoute: typeof WinesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wineries/$id/': {
      id: '/wineries/$id/'
      path: '/wineries/$id'
      fullPath: '/wineries/$id'
      preLoaderRoute: typeof WineriesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wines/$id/edit': {
      id: '/wines/$id/edit'
      path: '/wines/$id/edit'
      fullPath: '/wines/$id/edit'
      preLoaderRoute: typeof WinesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wineries/$id/edit': {
      id: '/wineries/$id/edit'
      path: '/wineries/$id/edit'
      fullPath: '/wineries/$id/edit'
      preLoaderRoute: typeof WineriesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PairingRoute: PairingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  WineriesAddRoute: WineriesAddRoute,
  WinesAddRoute: WinesAddRoute,
  CellarsIndexRoute: CellarsIndexRoute,
  WineriesIndexRoute: WineriesIndexRoute,
  WinesIndexRoute: WinesIndexRoute,
  WineriesIdEditRoute: WineriesIdEditRoute,
  WinesIdEditRoute: WinesIdEditRoute,
  WineriesIdIndexRoute: WineriesIdIndexRoute,
  WinesIdIndexRoute: WinesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
