/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PairingRouteImport } from './routes/pairing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WinesIndexRouteImport } from './routes/wines/index'
import { Route as WinesAddRouteImport } from './routes/wines/add'
import { Route as WinesIdRouteImport } from './routes/wines/$id'
import { Route as WinesIdEditRouteImport } from './routes/wines/$id.edit'

const PairingRoute = PairingRouteImport.update({
  id: '/pairing',
  path: '/pairing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WinesIndexRoute = WinesIndexRouteImport.update({
  id: '/wines/',
  path: '/wines/',
  getParentRoute: () => rootRouteImport,
} as any)
const WinesAddRoute = WinesAddRouteImport.update({
  id: '/wines/add',
  path: '/wines/add',
  getParentRoute: () => rootRouteImport,
} as any)
const WinesIdRoute = WinesIdRouteImport.update({
  id: '/wines/$id',
  path: '/wines/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WinesIdEditRoute = WinesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => WinesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pairing': typeof PairingRoute
  '/wines/$id': typeof WinesIdRouteWithChildren
  '/wines/add': typeof WinesAddRoute
  '/wines': typeof WinesIndexRoute
  '/wines/$id/edit': typeof WinesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pairing': typeof PairingRoute
  '/wines/$id': typeof WinesIdRouteWithChildren
  '/wines/add': typeof WinesAddRoute
  '/wines': typeof WinesIndexRoute
  '/wines/$id/edit': typeof WinesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pairing': typeof PairingRoute
  '/wines/$id': typeof WinesIdRouteWithChildren
  '/wines/add': typeof WinesAddRoute
  '/wines/': typeof WinesIndexRoute
  '/wines/$id/edit': typeof WinesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pairing'
    | '/wines/$id'
    | '/wines/add'
    | '/wines'
    | '/wines/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pairing'
    | '/wines/$id'
    | '/wines/add'
    | '/wines'
    | '/wines/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/pairing'
    | '/wines/$id'
    | '/wines/add'
    | '/wines/'
    | '/wines/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PairingRoute: typeof PairingRoute
  WinesIdRoute: typeof WinesIdRouteWithChildren
  WinesAddRoute: typeof WinesAddRoute
  WinesIndexRoute: typeof WinesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pairing': {
      id: '/pairing'
      path: '/pairing'
      fullPath: '/pairing'
      preLoaderRoute: typeof PairingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wines/': {
      id: '/wines/'
      path: '/wines'
      fullPath: '/wines'
      preLoaderRoute: typeof WinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wines/add': {
      id: '/wines/add'
      path: '/wines/add'
      fullPath: '/wines/add'
      preLoaderRoute: typeof WinesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wines/$id': {
      id: '/wines/$id'
      path: '/wines/$id'
      fullPath: '/wines/$id'
      preLoaderRoute: typeof WinesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wines/$id/edit': {
      id: '/wines/$id/edit'
      path: '/edit'
      fullPath: '/wines/$id/edit'
      preLoaderRoute: typeof WinesIdEditRouteImport
      parentRoute: typeof WinesIdRoute
    }
  }
}

interface WinesIdRouteChildren {
  WinesIdEditRoute: typeof WinesIdEditRoute
}

const WinesIdRouteChildren: WinesIdRouteChildren = {
  WinesIdEditRoute: WinesIdEditRoute,
}

const WinesIdRouteWithChildren =
  WinesIdRoute._addFileChildren(WinesIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PairingRoute: PairingRoute,
  WinesIdRoute: WinesIdRouteWithChildren,
  WinesAddRoute: WinesAddRoute,
  WinesIndexRoute: WinesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
